### ISSUE TITLE
A typo in your paper

### ISSUE THREAD

**Issue by nquesada** [iitis/IntU#1]
I am looking at the published version of your paper, in particular the following equation:

![image](https://user-images.githubusercontent.com/991946/183162145-c46815a3-b0fc-4e0d-bd33-d210ef466229.png)

At the end of the second line there is a plus, and the beginning of thethird there is a minus, which one is it?

**Comment by nquesada** [comment]
From some small unit test it seems like it is a minus, but would be great to get your confirmation

**Comment by jmiszczak** [comment]
Hi, it should be minus, everything is OK.
